### ISSUE TITLE
how to configure  "elasticsearch-data-import-handler"  with elastic search ?

### ISSUE THREAD

**Issue by dileepnarne** [kohesive/elasticsearch-data-import-handler#36]
Hai,

 I am new to elastic search ,  please let me know how to map this with elastic search .
I am would like import data from Oracle db to Elastic search using "elasticsearch-data-import-handler".
How to configure ?

Thank in advance

Regards
Dileep.

**Comment by apatrida** [comment]
Did you read the README file that shows examples of using other databases and connecting to Elasticsearch?
