### ISSUE TITLE
Huge data set

### ISSUE THREAD

**Issue by janhoy** [kohesive/elasticsearch-data-import-handler#39]
If I import a huge data set from SQL, will it need to first create a temporary Spart table before ingesting into ES? Or does it chunk things up so it does not require huge amount of RAM and/or DISK while importing?
Also, is there some way to support full vs incremental import, i.e. different SQL statement to only select what has changed since last ingest?

**Comment by apatrida** [comment]
@janhoy sorry for the delay in seeing this.  Did you figure out the issues?

If you create a query that is cached, you can define how it is cached (memory, disk, ...).  Normal Spark settings apply, and there are links from the README on the topic of memory settings and caching.

Full/Incremental is covered in the docs using `lastRun` and `thisRun` variables, when run without any state it will cause a full load.  Then every future run will be incremental.  You can delete the state for the target index to cause a full load again.
